import type { ColumnConfig } from '../types';

export const columns: ColumnConfig[] = [
  // Vendor & Model : pas de largeur fixe — elles se dimensionnent au contenu
  // (table-layout: auto). L'offset sticky de Model est calculé dynamiquement
  // dans TableView (mesure de la largeur rendue de Vendor).
  { key: 'vendor', label: 'Vendor', sortable: true, filterable: true, pinned: true },
  { key: 'model', label: 'Model', sortable: true, filterable: true, pinned: true },
  { key: 'reference', label: 'Reference', sortable: true, filterable: true, width: 156 },
  { key: 'antenna_type', label: 'Antenna Type', sortable: true, filterable: true, width: 600 },
  { key: 'indoor_outdoor', label: 'Indoor/Outdoor', sortable: true, filterable: true, width: 186 },
  { key: 'generation', label: 'Generation', sortable: true, filterable: true, width: 212 },
  { key: 'chipset', label: 'Chipset', sortable: true, filterable: true, width: 212 },
  { key: 'product_positioning', label: 'Product Positioning', sortable: true, filterable: true, width: 231 },
  { key: 'total_phy_serving_radios', label: 'Total PHY Serving Radios', sortable: true, filterable: true, width: 276 },
  { key: 'concurrent_serving_radios', label: 'Concurrent Serving Radios', sortable: true, filterable: false, width: 285 },
  { key: 'serving_radio_1', label: 'Serving Radio 1', sortable: true, filterable: true, width: 520 },
  { key: 'serving_radio_2', label: 'Serving Radio 2', sortable: true, filterable: true, width: 500 },
  { key: 'serving_radio_3', label: 'Serving Radio 3', sortable: true, filterable: true, width: 480 },
  { key: 'serving_radio_4', label: 'Serving Radio 4', sortable: true, filterable: true, width: 195 },
  { key: 'dedicated_scanning_radio', label: 'Dedicated Scanning Radio', sortable: true, filterable: true, width: 276 },
  { key: 'poe_class', label: 'PoE Class', sortable: true, filterable: true, width: 420 },
  { key: 'max_poe_consumption_w', label: 'Max PoE Consumption (W)', sortable: true, filterable: false, width: 300 },
  { key: 'limited_capabilities_poe_bt', label: 'Limited PoE BT', sortable: true, filterable: true, width: 303 },
  { key: 'limited_capabilities_poe_at', label: 'Limited PoE AT', sortable: true, filterable: true, width: 680 },
  { key: 'limited_capabilities_poe_af', label: 'Limited PoE AF', sortable: true, filterable: true, width: 780 },
  { key: 'ethernet1', label: 'Ethernet 1', sortable: true, filterable: true, width: 160 },
  { key: 'ethernet2', label: 'Ethernet 2', sortable: true, filterable: true, width: 470 },
  { key: 'weight_kg', label: 'Weight (kg)', sortable: true, filterable: false, width: 160 },
  { key: 'dimensions_cm', label: 'Dimensions (cm)', sortable: false, filterable: false, width: 204 },
  { key: 'geolocation', label: 'Geolocation', sortable: true, filterable: true, width: 196 },
  { key: 'usb_ports', label: 'USB Ports', sortable: true, filterable: false, width: 141 },
  { key: 'uwb', label: 'UWB', sortable: true, filterable: true, width: 100 },
  { key: 'gnss', label: 'GNSS', sortable: true, filterable: true, width: 100 },
  { key: 'bluetooth', label: 'Bluetooth', sortable: true, filterable: true, width: 220 },
  { key: 'zigbee', label: 'Zigbee', sortable: true, filterable: true, width: 220 },
  { key: 'minimum_software_version', label: 'Min Software Version', sortable: true, filterable: true, width: 276 },
  { key: 'maximum_software_version', label: 'Max Software Version', sortable: true, filterable: true, width: 276 },
  { key: 'end_of_sale_date', label: 'End of Sale Date', sortable: true, filterable: true, width: 204 },
  { key: 'end_of_support_date', label: 'End of Support Date', sortable: true, filterable: true, width: 240 },
  { key: 'public_price_usd', label: 'Price (USD)', sortable: true, filterable: false, width: 204 },
  { key: 'public_price_eur', label: 'Price (EUR)', sortable: true, filterable: false, width: 204 },
  { key: 'comments', label: 'Comments', sortable: false, filterable: true, width: 800 },
];

